---
# tasks file for liferay_application_infrastructure
- name: LifeRay Application Infrastructure Deployment Property File Loading
  include_vars:
          file: files/liferay_{{ env_name }}_data_dict.yaml
- name: LifeRay Application Infrastructure Deployment Task
  include_tasks: tasks/liferay-app-install-playbook.yaml
